name: initiation_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  badges: ^3.1.2
  cloud_firestore: ^5.6.3
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  go_router: ^14.7.2
  http: ^1.3.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
